### ISSUE TITLE
Mise en Production - v1.0.2

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-identite#113]
# Avant deploiement :
- [x] configurer le compte [authentification@beta.gouv.fr](mailto:authentification@beta.gouv.fr)
- [x] #133
- [x] tchapgouv/tchap-identite#125
- [x] https://github.com/tchapgouv/tchap-identite/issues/128
- ajouter les variables d'environnement 
    - [x] TCHAP_BOT_ACCOUNT_EMAIL : voir dashlane
    - [x] TCHAP_BOT_PASSWORD : voir dashlane
    - [x] KEYCLOAK_VERSION=18.0.1
    - [x] TCHAP_HOME_REDIRECT_URL=https://audioconf.numerique.gouv.fr/questions-frequentes#qui-peut-avoir-acces
    - [x] KC_SPI_THEME_WELCOME_THEME=tchap-otp-login
    - [x] KC_LOG_LEVEL=INFO,org.beta:INFO,org.beta.authentification.keycloak:DEBUG,org.keycloak.services:ERROR
    - [x] QUARKUS_EXTENSIONS_DIR=dev/quarkus-extensions
    - [x] FEATURE_TCHAP_BOT_OTP=true
    - [x] quarkus_log_sentry=true
    - [x] quarkus_log_sentry_dsn=https://
    - [x] quarkus_log_sentry_minimum_event_level=WARN
    - [x] quarkus_log_sentry_in_app_packages=*
    - [x] quarkus_log_sentry_server_name=tchap-id-prod
    - [x] quarkus_log_sentry_environment=prod
    - [x] FEATURE_HEALTHY_HOME_SERVER_STRATEGY=true
    - [x] FEATURE_REUSE_MATRIX_SERVICE=false
    - [x] TCHAP_HOME_SERVER_LIST= agent.tchap.gouv.fr,agent.agriculture.tchap.gouv.fr,agent.collectivites.tchap.gouv.fr,agent.culture.tchap.gouv.fr,agent.dev-durable.tchap.gouv.fr,agent.dinum.tchap.gouv.fr,agent.diplomatie.tchap.gouv.fr,agent.education.tchap.gouv.fr,agent.elysee.tchap.gouv.fr,agent.externe.tchap.gouv.fr,agent.finances.tchap.gouv.fr,agent.intradef.tchap.gouv.fr,agent.justice.tchap.gouv.fr,agent.pm.tchap.gouv.fr,agent.social.tchap.gouv.fr,agent.ssi.tchap.gouv.fr

- [x] Faire la livraison: 
   - [x] https://github.com/tchapgouv/tchap-identite/pull/156
   - [x] https://github.com/tchapgouv/tchap-identite/pull/164
## Taches independante
- [x] tchapgouv/tchap-infra#1159

# Apres deploiement :    
- [x] tchapgouv/tchap-identite#124 
- [x] https://github.com/tchapgouv/tchap-infra/issues/1141  
- [ ] backup realm 
- [x] - supprimer les variables d'environnement : 
    - [x] TCHAP_ACCOUNT
    - [x] TCHAP_PASSWORD
    - [x] TCHAP_MATRIX_ID

**Comment by pseudonyme21** [comment]
Dans tchap le bot sera authentification [authentification] si on prend l'adresse authentification@authentification.beta.gouv.fr
C'est pas un peu bizarre non?

**Comment by pseudonyme21** [comment]
Autre choix : bot@authentification.beta.gouv.fr pour avoir bot [authentification] dans tchap

**Comment by estellecomment** [comment]
Je sais pas si le mot "bot" est pas familier pour un public non-tech. "Robot" ?

**Comment by odelcroi** [comment]
d'accord, dans ce cas, allons vers le mega obvious `code [authentification]`

**Comment by Caroline-lawson** [comment]
Je suis d'accord avec pas de "bot" ni de "robot", mai splutôt "code [authentification]".

Ca correspond mieux à ce que les participants m'ont dit.

**Comment by jdauphant** [comment]
Ça sera Authentification [Beta] le nom du compte avec l'adresse que j'ai indiqué

**Comment by jdauphant** [comment]
Vous pouvez aussi demander au Ops de mettre le label que vous souhaitez

**Comment by Caroline-lawson** [comment]
On pourrait assurer que le display name est le même dans Tchap et le mail ?

**Comment by odelcroi** [comment]
Le display name dans le bot tchap est générique, il sera "Authentification", alors que dans le mail, on a la possibilité de le personnaliser pour chaque application, il est donc AudioConf. Is it bad?

**Comment by JDixmier** [comment]
Le bot fait flipper les utilisateurs

![Capture d’écran 2022-07-11 à 15 09 37](https://user-images.githubusercontent.com/45665538/178273760-6548bca5-f1f6-4f72-a973-c8f28008ce24.png)


Est-ce que techniquement il serait possible de personnaliser le display name du bot en fonction du service pour lequel Tchap ID aura été utilisé ? 

Ce serait peut-être moins déroutant pour les utilisateurs de recevoir un message de  "AudioConf - Authentification", car ça correspond à leur contexte immédiat
